Fix coala/landing-frontend#189
coala/coalaCSS pull request #14
Opened 2017-07-02 08:44 UTC by raghavmittal101

Added `overflow-x` property to `.coafile` .

2017-07-03 23:00 UTC, hemangsk commented
Please get assigned to the issue you are fixing, for that you can go on gitter and say Hello World, you will get an email invite to join coala org :)

2017-07-04 04:16 UTC, raghavmittal101 commented
Thank you for kind help. I have followed the steps you suggested and assigned this issue to myself.

2017-07-04 09:02 UTC, hemangsk requested changes

2017-07-04 09:02 UTC, hemangsk commented on coala.css
>    white-space: pre-line;
overflow-x: auto should go inside the ```.coala-online .coafile```  selector

2017-07-04 09:40 UTC, hemangsk approved these changes

2017-07-04 09:41 UTC, hemangsk commented
@raghavmittal101 awesome, just one more request to squash both of the commits into one, and to follow the commit message guidelines on https://coala.io/commit

2017-07-05 13:43 UTC, Arsfiqball commented
@raghavmittal101 you need to squash your commit.

2017-07-05 14:37 UTC, raghavmittal101 commented
I have created a new pull request from another branch here https://github.com/coala/coalaCSS/pull/16. Please consider that one. Sorry for creating all this mess and wasting precious time of the community members.

2017-07-07 02:37 UTC, yukiisbored commented
Closing for newer PR https://github.com/coala/coalaCSS/pull/16. Also, @raghavmittal101 here's a tip Github doesn't care about the branch at all it just only see the name, You can just copy your work over to another branch, destroy the old one that's being used in the PR, create a new one, cherry pick the commits from the other branch (you can modify them if you wish!), and do a force push to the same branch name. et Voila! no need to create new pull requests!

Feel free to ask us questions about git and the tools that we use on our gitter channels :)

2017-07-07 02:38 UTC, closed without merging

2017-07-07 07:04 UTC, raghavmittal101 commented
@yukiisbored and @Arsfiqball Thank you for helping m. :) . I am using github since a couple of years, but never worked with opensource organizations like coala. Its a nice experience. :sweat_smile: