Fix title font size for small screen devices
coala/coalaCSS pull request #24
Opened 2017-11-03 09:39 UTC by utkarsh23

Resolved issue #23 

Before:
![first](https://user-images.githubusercontent.com/12075549/32367468-356de6a6-c0a8-11e7-8cb9-e9b467226b42.png)

After:
![after](https://user-images.githubusercontent.com/12075549/32367616-b487bac0-c0a8-11e7-81c7-fd570e5ef55e.png)

2017-11-03 15:36 UTC, newbazz commented
Write the "Closes <issue link>" in the commit.

2017-11-03 16:48 UTC, danishprakash reviewed
Always read [coala commit writing guidelines](http://api.coala.io/en/latest/Developers/Writing_Good_Commits.html) before commiting. Kindly change your commit according to the guidelines.
Until then, wait for someone with appropriate permissions to review the PR. 👍

2017-11-05 05:27 UTC, jayvdb requested changes

2017-11-05 05:27 UTC, jayvdb commented on coala.css
> +
we dont want two blank lines here.

2017-11-05 11:27 UTC, utkarsh23 commented
@jayvdb its fixed

2017-11-05 15:54 UTC, jayvdb requested changes
Please squash your commits.

2017-11-05 21:35 UTC, utkarsh23 commented
@jayvdb squashed the two commits :+1:

2017-11-06 19:27 UTC, newbazz reviewed
Use "Fixes" instead of "Closes" in commit message.

2017-11-17 06:37 UTC, yashovardhanagrawal commented
Your code looks fine, but please follow the [commit guidelines](http://api.coala.io/en/latest/Developers/Writing_Good_Commits.html). Your commit description's first line is too long, please reduce the number of characters in the first line as according to commit guidelines only 72 characters are allowed per line.

2017-11-17 06:38 UTC, yashovardhan requested changes
unack https://github.com/coala/coalaCSS/pull/24/commits/334696fd677149e8a0e06dcfe48d27b4878bb8f0

2017-11-20 21:44 UTC, Monal5031 commented
@utkarsh23 Use `Closes` in the commit message body.

2017-11-21 04:10 UTC, jayvdb commented
unack https://github.com/coala/coalaCSS/pull/24/commits/7e57de9428552990f2ba5d801b4e59d80df64b0e

2017-12-03 11:56 UTC, utkarsh23 commented
Is there more work to be done on this PR? I believe I've fixed everything @jayvdb

2017-12-03 13:59 UTC, realslimshanky requested changes
Your commit message has a shortlog of 55 characters which should be a maximum of 50. Please follow [this](https://api.coala.io/en/latest/Developers/Writing_Good_Commits.html) documentation on writing a good commit message. Amend your commit and push it again.

2017-12-04 19:56 UTC, Monal5031 approved these changes
LGTM :+1:

2017-12-04 19:57 UTC, Monal5031 commented
ack de3776e

2017-12-04 20:33 UTC, realslimshanky approved these changes

2017-12-09 18:03 UTC, hemangsk commented
@gitmate-bot rebase

2017-12-09 18:04 UTC, hemangsk commented
@rultor merge 🎉

2017-12-09 18:05 UTC, rultor commented
> @rultor merge 🎉 

@hemangsk OK, I'll try to merge now. You can check the progress of the merge [here](http://www.rultor.com/t/13556-350494683)

2017-12-09 18:06 UTC, rultor commented
> @rultor merge 🎉 

@hemangsk @utkarsh23 Oops, I failed. You can see the full log [here](http://www.rultor.com/t/13556-350494683) (spent 2min)

```
-rwxrwxr-x  1 rultor rultor  338 Dec  9 19:05 entry.sh
-rw-rw-r--  1 rultor rultor    6 Dec  9 19:05 pid
drwxrwxr-x  3 rultor rultor 4096 Dec  9 19:05 repo
-rwxrwxr-x  1 rultor rultor 5444 Dec  9 19:05 run.sh
-rw-rw-r--  1 rultor rultor  434 Dec  9 19:05 script.sh
-rw-rw-r--  1 rultor rultor 4368 Dec  9 19:05 stdout
++ pwd
++ pwd
+ docker run -t --rm -v /tmp/rultor-Xdf5:/main --env=fork=git@github.com:utkarsh23/coalaCSS.git --env=fork_branch=utkarsh23-patch --env=head=git@github.com:coala/coalaCSS.git --env=head_branch=master --env=pull_id=24 '--env=pull_title=Fix title font size for small screen devices' --env=author=hemangsk '--env=scripts=( '\''export '\''\'\'''\''fork=git@github.com:utkarsh23/coalaCSS.git'\''\'\'''\'''\'' '\'';'\'' '\''export '\''\'\'''\''fork_branch=utkarsh23-patch'\''\'\'''\'''\'' '\'';'\'' '\''export '\''\'\'''\''head=git@github.com:coala/coalaCSS.git'\''\'\'''\'''\'' '\'';'\'' '\''export '\''\'\'''\''head_branch=master'\''\'\'''\'''\'' '\'';'\'' '\''export '\''\'\'''\''pull_id=24'\''\'\'''\'''\'' '\'';'\'' '\''export '\''\'\'''\''pull_title=Fix title font size for small screen devices'\''\'\'''\'''\'' '\'';'\'' '\''export '\''\'\'''\''author=hemangsk'\''\'\'''\'''\'' '\'';'\'' '\''echo "Nothing to do."'\'' '\'';'\'' )' --hostname=docker --privileged --memory=6g --memory-swap=16g --oom-kill-disable --cidfile=/tmp/rultor-Xdf5/cid -w=/main --name=coala_coalacss_24 yegor256/rultor /main/entry.sh
WARNING: Your kernel does not support swap limit capabilities or the cgroup is not mounted. Memory limited without swap.
+ set -e
+ set -o pipefail
+ shopt -s dotglob
+ useradd -m -G sudo r
+ echo '%sudo ALL=(ALL) NOPASSWD:ALL'
+ cp -R /root/.bashrc /root/.composer /root/.gem /root/.gnupg /root/.m2 /root/.profile /root/texmf /home/r
+ cp -R ./cid ./end.sh ./entry.sh ./pid ./repo ./run.sh ./script.sh ./stdout /home/r
+ rm -rf repo
+ chown -R r:r /home/r
+ chmod a+x /home/r/script.sh
+ su --login r --command /home/r/script.sh
+ set -e
+ set -o pipefail
+ shopt -s expand_aliases
+ alias 'sudo=sudo -i'
+ export HOME=/home/r
+ HOME=/home/r
+ cd /home/r/repo
+ export fork=git@github.com:utkarsh23/coalaCSS.git
+ fork=git@github.com:utkarsh23/coalaCSS.git
+ export fork_branch=utkarsh23-patch
+ fork_branch=utkarsh23-patch
+ export head=git@github.com:coala/coalaCSS.git
+ head=git@github.com:coala/coalaCSS.git
+ export head_branch=master
+ head_branch=master
+ export pull_id=24
+ pull_id=24
+ export 'pull_title=Fix title font size for small screen devices'
+ pull_title='Fix title font size for small screen devices'
+ export author=hemangsk
+ author=hemangsk
+ echo 'Nothing to do.'
Nothing to do.
+ mv /home/r/repo .
++ whoami
+ chown -R root repo
+ '[' -n '' ']'
++ whoami
+ sudo chown -R rultor repo
+ cd repo
+ git push origin master
ERROR: Permission to coala/coalaCSS.git denied to rultor.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
container 6b92000519c44c3132820d8bcb5009bce4123a0b72521779b9d5f194fbbd4a9e is dead
Sat Dec  9 19:06:35 CET 2017

```

2017-12-09 18:07 UTC, merged