coala.css: Add chip width
coala/coalaCSS pull request #35
Opened 2018-11-21 19:16 UTC by bharatpurohit97

this addition of width ensures that-
links below title are proper in mobile view.
Assigning value max-content display links in all screen sizes.

Fixes https://github.com/coala/landing-frontend/issues/85

2018-11-21 22:17 UTC, SerekKiri requested changes
One more time, changes seems good but the commit massage is too long :wink:

2018-11-22 00:17 UTC, CLiu13 commented
@SerekKiri Commit message seems OK to me - seems to follow all of the [guidelines](https://api.coala.io/en/latest/Developers/Writing_Good_Commits.html), but I may be missing something?

2018-11-22 08:09 UTC, SerekKiri commented
@CLiu13 Description have 142 characters, guideline said it should be 72.

2018-11-22 16:40 UTC, CLiu13 commented
@SerekKiri Guideline says `maximum of 72 characters per line`, not in total :)

2018-11-22 16:48 UTC, SerekKiri commented
> @SerekKiri Guideline says `maximum of 72 characters per line`, not in total :)

Nevermind I was reading that on mobile app and that looked like text without breake 😄

2018-11-22 18:33 UTC, hemangsk commented
ack a248e5f

2018-11-22 18:34 UTC, merged